export const BASE_METADATA = {
  authors: [{ name: "0xAlice" }],
  category: "Finance",
  creator: "0xAlice",
  keywords: [
    "wrap",
    "unwrap",
    "token",
    "exchange",
    "defi",
    "candywrap",
    "candy",
    "swap",
    "wrapped",
    "eth",
    "erc20",
    "ethereum",
    'wrapeth',
    'optimism',
    'arbitrum',
    'polygon',
    'bsc',
    'avalanche',
    'degen',
    'chain',
    'avax',
    'matic',
    'bnb',
    'binance',
    'smartchain',
    'fuse',
    'fantom',
  ],
  title: "CandyWrap",
  description:
    "Wrap and unwrap your ETH/WETH in a few clicks right from your wallet. Supports multiple chains. Swap now on Ethereum!",
};
