export const BASE_METADATA = {
  authors: [{ name: "0xAlice" }],
  category: "Finance",
  creator: "0xAlice",
  keywords: [
    "wrap",
    "unwrap",
    "token",
    "exchange",
    "defi",
    "candywrap",
    "candy",
    "swap",
    "wrapped",
    "eth",
    "erc20",
    "ethereum",
    "smart contract",
    "wrapeth",
    "optimism",
    "arbitrum",
    "polygon",
    "bsc",
    "avalanche",
    "avax",
    "wavax",
    "degen",
    "wdegen",
    "chain",
    "avax",
    "wavax",
    "matic",
    "wmatic",
    "bnb",
    "binance",
    "smartchain",
    "fuse",
    "fantom",
    "ftm",
    "wftm",
    "filecoin",
    "fil",
    "wfil",
    'zora',
    'scroll',
    'evm',
    'wan',
    'wwan',
    'movr',
    'wmovr',
    'glmr',
    'wglmr',
    'metis',
    'wmetis',
    'one',
    'wone',
    'canto',
    'wcanto'
  ],
  title: "CandyWrap",
  description:
    "Wrap and unwrap your ETH/WETH in a few clicks right from your wallet. Supports multiple chains. Instead of swapping for a high fee use this instead. Convert now on Ethereum!",
};
